services:

  composer:
    image: composer:latest
    profiles: [composer]
    working_dir: /app
    volumes:
      - .:/app
    command: install

  php:
    image: dunglas/frankenphp
    container_name: rw_environment
    ports:
      - "80:80"
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - .:/app/public
      - caddy_data:/data
      - caddy_config:/config
    tty: true

volumes:
  caddy_data:
  caddy_config: